In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in d:\college\3rd sem\python\.venv\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\college\3rd sem\python\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\college\3rd sem\python\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 953.4 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.8 MB 964.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.8 MB 964.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.8 MB 964.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.8 MB 964.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.8 MB 964.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.8 MB 964.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.8 MB 964.7 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/9.8 MB 437.8 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.8 MB 437.8 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.8 MB 437.8 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.8 MB 437.8 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.8 MB 437.8 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.8 MB 361.4 kB/s eta 0:00:24
   ----- ---------------------------------- 1.3/9.8 MB 361.4 kB/s eta 0:00:24
   ----- ---------------------------------- 1.3/9.8 MB 361.4 kB/s eta 0:00:24
   ----- ---------------------------------- 1.3/9.8 MB 361.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.8 MB 348.5 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.8 MB 348.5 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.8 MB 348.5 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.8 MB 348.5 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.8 MB 348.5 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.8 MB 348.5 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.8 MB 348.5 kB/s eta 0:00:24
   ------- -------------------------------- 1.8/9.8 MB 311.1 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.8 MB 311.1 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.8 MB 311.1 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.8 MB 311.1 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.8 MB 311.1 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.8 MB 311.1 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/9.8 MB 311.1 kB/s eta 0:00:26
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.8 MB 281.6 kB/s eta 0:00:28
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.8 MB 250.8 kB/s eta 0:00:30
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.8 MB 235.8 kB/s eta 0:00:31
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ----------- ---------------------------- 2.9/9.8 MB 217.5 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.8 MB 209.6 kB/s eta 0:00:32
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   ------------- -------------------------- 3.4/9.8 MB 192.4 kB/s eta 0:00:34
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   -------------- ------------------------- 3.7/9.8 MB 180.7 kB/s eta 0:00:35
   ---------------- ----------------------- 3.9/9.8 MB 179.7 kB/s eta 0:00:33
   ---------------- ----------------------- 3.9/9.8 MB 179.7 kB/s eta 0:00:33
   ---------------- ----------------------- 3.9/9.8 MB 179.7 kB/s eta 0:00:33
   ---------------- ----------------------- 3.9/9.8 MB 179.7 kB/s eta 0:00:33
   ---------------- ----------------------- 3.9/9.8 MB 179.7 kB/s eta 0:00:33
   ---------------- ----------------------- 3.9/9.8 MB 179.7 kB/s eta 0:00:33
   ---------------- ----------------------- 3.9/9.8 MB 179.7 kB/s eta 0:00:33
   ----------------- ---------------------- 4.2/9.8 MB 179.7 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.8 MB 179.7 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.8 MB 179.7 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.8 MB 179.7 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.8 MB 179.7 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.8 MB 179.7 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.8 MB 181.9 kB/s eta 0:00:30
   ------------------ --------------------- 4.5/9.8 MB 181.9 kB/s eta 0:00:30
   ------------------ --------------------- 4.5/9.8 MB 181.9 kB/s eta 0:00:30
   ------------------ --------------------- 4.5/9.8 MB 181.9 kB/s eta 0:00:30
   ------------------ --------------------- 4.5/9.8 MB 181.9 kB/s eta 0:00:30
   ------------------ --------------------- 4.5/9.8 MB 181.9 kB/s eta 0:00:30
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   ------------------- -------------------- 4.7/9.8 MB 182.8 kB/s eta 0:00:28
   -------------------- ------------------- 5.0/9.8 MB 180.8 kB/s eta 0:00:27
   -------------------- ------------------- 5.0/9.8 MB 180.8 kB/s eta 0:00:27
   -------------------- ------------------- 5.0/9.8 MB 180.8 kB/s eta 0:00:27
   -------------------- ------------------- 5.0/9.8 MB 180.8 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/9.8 MB 184.8 kB/s eta 0:00:25
   --------------------- ------------------ 5.2/9.8 MB 184.8 kB/s eta 0:00:25
   ---------------------- ----------------- 5.5/9.8 MB 191.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.8 MB 191.2 kB/s eta 0:00:23
   ----------------------- ---------------- 5.8/9.8 MB 197.4 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.8 MB 197.4 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.8 MB 197.4 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.8 MB 197.4 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.8 MB 197.4 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.8 MB 200.5 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.8 MB 200.5 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.8 MB 200.5 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.8 MB 200.5 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.8 MB 200.5 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.8 MB 200.5 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.8 MB 200.5 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.8 MB 192.4 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.8 MB 192.4 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.8 MB 192.4 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.8 MB 192.4 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.8 MB 192.4 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.8 MB 192.4 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.8 MB 185.9 kB/s eta 0:00:18
   -------------------------- ------------- 6.6/9.8 MB 185.9 kB/s eta 0:00:18
   -------------------------- ------------- 6.6/9.8 MB 185.9 kB/s eta 0:00:18
   -------------------------- ------------- 6.6/9.8 MB 185.9 kB/s eta 0:00:18
   --------------------------- ------------ 6.8/9.8 MB 186.7 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 186.7 kB/s eta 0:00:17
   --------------------------- ------------ 6.8/9.8 MB 186.7 kB/s eta 0:00:17
   ---------------------------- ----------- 7.1/9.8 MB 188.5 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.8 MB 188.5 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.8 MB 188.5 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.8 MB 188.5 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.8 MB 188.5 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.8 MB 188.5 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.8 MB 189.0 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.8 MB 189.0 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.8 MB 189.0 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.8 MB 189.0 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.8 MB 189.0 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.8 MB 189.0 kB/s eta 0:00:14
   ------------------------------ --------- 7.6/9.8 MB 191.6 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.8 MB 191.6 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.8 MB 191.6 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.8 MB 191.6 kB/s eta 0:00:12
   -------------------------------- ------- 7.9/9.8 MB 194.2 kB/s eta 0:00:11
   -------------------------------- ------- 7.9/9.8 MB 194.2 kB/s eta 0:00:11
   -------------------------------- ------- 7.9/9.8 MB 194.2 kB/s eta 0:00:11
   -------------------------------- ------- 7.9/9.8 MB 194.2 kB/s eta 0:00:11
   --------------------------------- ------ 8.1/9.8 MB 201.0 kB/s eta 0:00:09
   --------------------------------- ------ 8.1/9.8 MB 201.0 kB/s eta 0:00:09
   ---------------------------------- ----- 8.4/9.8 MB 207.1 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.8 MB 207.1 kB/s eta 0:00:07
   ----------------------------------- ---- 8.7/9.8 MB 213.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.8 MB 213.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.8 MB 213.1 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.8 MB 213.1 kB/s eta 0:00:06
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.8 MB 219.8 kB/s eta 0:00:05
   ------------------------------------- -- 9.2/9.8 MB 222.9 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 222.9 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 222.9 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 222.9 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.8 MB 222.9 kB/s eta 0:00:03
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.8 MB 223.7 kB/s eta 0:00:02
   ---------------------------------------  9.7/9.8 MB 224.7 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 224.7 kB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 226.1 kB/s eta 0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

# Pandas

### data and tables

In [3]:
import pandas as pd
data = {
    "name":["vicky","manu","virat"],
    "age":[21,22,45],
    "marks":[1,4,6]
}
df=pd.DataFrame(data)

In [4]:
df

    name  age  marks
0  vicky   21      1
1   manu   22      4
2  virat   45      6

### CSV file

In [5]:
pip install requests

Collecting requests
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.9-cp313-cp313-win_amd64.whl.metadata (42 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading charset_normalizer-3.4.9-cp313-cp313-win_amd64.whl (161 kB)
Downloading idna-3.18-py3-none-any.whl (65 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
Successfully installed certifi-2026.7.22 charset_normalizer-3.4.9 idna-3.18 requests-2.34.2 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import requests
from io import StringIO

In [8]:
url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
req = requests.get(url, headers=headers)
data = StringIO(req.text)
pd.read_csv(data)

     Index   Height(Inches)"   "Weight(Pounds)"
0        1             65.78             112.99
1        2             71.52             136.49
2        3             69.40             153.03
3        4             68.22             142.34
4        5             67.79             144.30
..     ...               ...                ...
195    196             65.80             120.84
196    197             66.11             115.78
197    198             68.24             128.30
198    199             68.02             127.47
199    200             71.39             127.88

[200 rows x 3 columns]

### Sep Parameter

In [ ]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=[])

FileNotFoundError: [Errno 2] No such file or directory: 'movie_titles_metadata.tsv'

### index_col Parameter

In [10]:
pd.read_csv('aug_train.csv',index_col='city')

FileNotFoundError: [Errno 2] No such file or directory: 'aug_train.csv'